language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
  - PACT_BROKER_BASE_URL=https://alombardi.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "tcxrzjoIK9qiZfbkxTf6NoqUZFsL+R7MGiv5N/xMRFgNmCXvUf18Pr3LjikuVYxx0cpPTYYoma1qKD2tbU0pvkJV4ut/sL7FyGH48WKTg+Nhrx4fTgD1Nz1JJzSKivU4HBh/jFhgmbz4SLsml7uLI3R135arp60VvGcIOEVFeSuhtoGNTORJ2pdKnadJ7xw4lIBKjtn8Hu2c1CBJfHpEQJyRD+qBeth1aAgaIapAjhUA5qAZYxRLsr9V656P6YtDN6RMNp+2LtpOtgXsV6eBWCApWepaxMb4ICih90F+jNCjVBMp5itI3wwcjAXaYzEAoRw4uwpUl9q7cPuKWOhNGAY9F7niU3NV7plR7kL/5fDVnyx4lhHybjrr8/4qstYrQ6+h2yQpR482wlrY8oMQu228mg5LhPPA0PduInjn/SgvtyZ6Zv40xJQudrYpTCP15D1zTZoIOYcqv+lKzxk6RhsSF5TsBB99CpuHk5+7EvEoXu0qrgxmyAzTv6zGM7v8LOrbjJv97d1IOvVyP43XboVQ5XUKZNmY9VUM42B4FfHxMk0lZXgzLd6+msrUARoQKmjYGNLLw8VVp5u6V71V4QixsoD9IbdlbXvMxuNkzTcj8eA4RSFrt+IXIMRLzF3pyTwvkaOyt6LO9YgXZcg0VnzCsQw9eBu82MPX+MQAh54="
   - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
